# Package building stuff - Experimental!
SET(CPACK_PACKAGE_VERSION "${QUADMAP_VERSION}")
SET(CPACK_PACKAGE_VERSION_MAJOR "${QUADMAP_MAJOR_VERSION}")
SET(CPACK_PACKAGE_VERSION_MINOR "${QUADMAP_MINOR_VERSION}")
SET(CPACK_PACKAGE_VERSION_PATCH "${QUADMAP_PATCH_VERSION}")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "CMake ${V_MAJOR}.${V_MINOR}")
SET(CPACK_PACKAGE_CONTACT "Youngsun kwon, Donghyuk Kim, and Sung-Eui Yoon")
SET(CPACK_PACKAGE_VENDOR "KAIST(Korea Advanced Institute of Science and Technology)")
SET(CPACK_GENERATOR "DEB")
SET(CPACK_SOURCE_GENERATOR "TGZ")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME
  "${PROJECT_NAME}-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")

 # This must always be last statement!
INCLUDE(CPack)

